#!/usr/bin/env ANSIBLE_HOSTS="localhost," ANSIBLE_CONNECTION=local ansible-playbook
# vim:ft=yaml
---
- name: install apple defaults
  hosts: localhost

  tasks:
    - name: com.apple.desktopservices
      osx_defaults:
          domain: com.apple.desktopservices
          state: present
          key: "{{ item.key }}"
          type: "{{ item.type }}"
          value: "{{ item.value }}"
      with_items:
      - { key: "DSDontWriteUSBStores", type: "bool", value: "true" }
