#!/usr/bin/env ANSIBLE_HOSTS="localhost," ANSIBLE_CONNECTION=local ansible-playbook
# vim:ft=yaml
---
- name: install apple defaults
  hosts: localhost

  tasks:
  - name: Set ScreenSharing settings
    osx_defaults:
        domain: com.apple.ScreenSharing
        state: present
        key: "{{ item.key }}"
        type: "{{ item.type }}"
        value: "{{ item.value }}"
    with_items:
      - { key: "DontQuitWhenLastWindowCloses", type: "bool", value: "true" }
