#!/usr/bin/env ANSIBLE_HOSTS="localhost," ANSIBLE_CONNECTION=local ansible-playbook
# vim:ft=yaml
---
- name: install RemoteDesktop defaults
  hosts: localhost
  vars:
  tasks:
    - name: Set Remote Desktop defaults
      osx_defaults:
        domain: com.apple.RemoteDesktop
        state: present
        key: "{{ item.key }}"
        type: "{{ item.type }}"
        value: "{{ item.value }}"
      with_items:
        - { key: "doubleClickAction", type: "string", value: "Control" }
        - { key: "encryptCopy", type: "bool", value: "false" }
        - { key: "encryptInstall", type: "bool", value: "false" }
        - { key: "sendTaskNotification", type: "bool", value: "false" }
        - { key: "serverGroupOpen", type: "bool", value: "false" }
        - { key: "useEncryptedTunnel", type: "bool", value: "false" }
        - { key: "useKeychain", type: "bool", value: "false" }
