#!/usr/bin/env ANSIBLE_HOSTS="localhost," ANSIBLE_CONNECTION=local ansible-playbook
# vim:ft=yaml
---
- name: install apple defaults
  hosts: localhost

  tasks:
    - name: com.apple.driver.AppleBluetoothMultitouch.trackpad
      osx_defaults:
          domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
          state: present
          key: "{{ item.key }}"
          type: "{{ item.type }}"
          value: "{{ item.value }}"
      with_items:
      - { key: "TrackpadPinch", type: "int", value: "0" }
      - { key: "Clicking", type: "bool", value: "true" }
