#!/usr/bin/env ANSIBLE_HOSTS="localhost," ANSIBLE_CONNECTION=local ansible-playbook
# vim:ft=yaml
---
- name: install safari defaults
  hosts: localhost
  vars:
  tasks:
    - name: com.github.GitHub
      osx_defaults:
        domain: com.github.GitHub
        state: present
        key: "{{ item.key }}"
        type: "{{ item.type }}"
        value: "{{ item.value }}"
      with_items:
      - { key: "GitHubAppDelegateDefaultLocalPathKey", type: "string", value: "/Users/brian/GitHub" }
      - { key: "NSNavLastRootDirectory", type: "string", value: "~/GitHub" }
      - { key: "commitAndSyncEnabled", type: "int", value: "1" }
      - { key: "NSNavPanelExpandedStateForSaveMode", type: "int", value: "1" }
