---
- name: Common Play
  hosts: localhost
  connection: local

  tasks:
    - name: update brew
      homebrew: update_homebrew=yes upgrade_all=yes

    - name: install osx build software
      homebrew: name={{ item }} state=present
      with_items:
        - autoconf
        - autoconf-archive
        - automake
        - boost
        - byobu
        - diffuse
        - gettext
        - hub 
        - intltool
        - libevent
        - libmemcached
        - libtool
        - mysql
        - npm
        - lldpd
        - pcre
        - protobuf
        - pwgen
        - qemu
        - shellcheck
        - splint
        - ssh-copy-id
        - swig
        - libyaml
        - yubico-piv-tool
        - yubikey-personalization


    - name: Install from dupes
      homebrew_tap: name={{ item }}
                    state=present
      with_items:
        - homebrew/dupes
        - caskroom/cask

    - name: install brew cask
      command: brew install brew-cask

# This is because not everything will install
    - name: install bison and friends for OSX
      ignore_errors: yes
      homebrew: name={{ item }}
                state=present
      with_items:
        - bison
        - flex
        - gperf

    - name: install osx brew cask software
      homebrew_cask: name={{ item }} state=present
      with_items:
        - dropbox
        - flash
        - github
        - google-chrome
        - google-drive
        - java
        - vmware-fusion
        - gpgtools
        - macpass
        - yubikey-neo-manager
        - yubikey-personalization-gui
        - yubikey-piv-manager
        - microsoft-lync
        - microsoft-office

    - name: brew linkapps
      command: brew linkapps
    - name: install keybase-installer
      command: npm install -g keybase-installer
    - name: install keybase
      command: keybase-installer
    - name: disable hidden files on network filesystems
      command: defaults write com.apple.desktopservices DSDontWriteNetworkStores true
    - name: install pip
      easy_install:
          name: pip
          state: present
    - name: pip installs required python libraries
      pip: 
          name: "{{ item }}"
          state: present
      with_items:
      - virtualenv
      - setuptools
      - requests[security]
