#!/usr/bin/env ansible-playbook
---
- name: Common Play
  hosts: all
  connection: local

  roles:
  - common

  tasks:
# This is because not everything will install
    - name: install bison and friends for OSX
      ignore_errors: yes
      homebrew: name={{ item }}
                state=present
      with_items:
        - bison
        - flex
        - gperf
        - engine_pkcs11

    - name: install osx brew cask software
      homebrew_cask: name={{ item }} state=present
      with_items:
        - dropbox
        - flash
        - geektool
        - github
        - google-chrome
        - google-drive
        - gpgtools
        - java
        - macpass
        - microsoft-lync
        - microsoft-office
        - rcdefaultapp
        - secrets
        - vmware-fusion
        - yubikey-neo-manager
        - yubikey-personalization-gui
        - yubikey-piv-manager

    - name: brew linkapps
      command: brew linkapps
    - name: install keybase-installer
      command: npm install -g keybase-installer
    - name: install keybase
      command: keybase-installer
    - name: disable hidden files on network filesystems
      command: defaults write com.apple.desktopservices DSDontWriteNetworkStores true
    - name: install pip
      sudo: True
      easy_install:
          name: pip
          state: present
    - name: pip installs required python libraries
      sudo: True
      pip: 
          name: "{{ item }}"
          state: present
      with_items:
      - virtualenv
      - setuptools
      - requests[security]
