#!/usr/bin/env ansible-playbook
---
- name: Common Play
  hosts: all
  connection: local

  tasks:
    - name: update brew
      homebrew:
        update_homebrew: yes
        upgrade_all: yes

    - name: Install from dupes
      homebrew_tap:
        name: "{{ item }}"
        state: present
      with_items:
        - homebrew/dupes
        - caskroom/cask
        - homebrew/fuse
        - homebrew/completions
        - homebrew/command-not-found

    - name: install osx build software
      homebrew: name={{ item }} state=present
      with_items:
        - autoconf
        - autoconf-archive
        - automake
        - boost
        - byobu
        - cdrtools
        - diffuse
        - gettext
        - hub
        - intltool
        - libevent
        - libmemcached
        - libtool
        - mysql
        - npm
        - osxfuse
# lldpd seems to be constantly having issues
#       - lldpd
        - pcre
        - protobuf
        - pwgen
        - qemu
        - shellcheck
        - splint
        - ssh-copy-id
        - sshfs
        - swig
        - libyaml
        - yubico-piv-tool
        - yubikey-personalization

    - name: install brew cask
      command: brew install brew-cask
      tags:
          - skip_ansible_lint

    - name: install osx brew cask software
      homebrew_cask: name={{ item }} state=present
      with_items:
        - apm-bash-completion
        - brew-cask-completion
        - launchctl-completion
        - open-completion
        - pip-completion

# This is because not everything will install
#    - name: install osx brew cask software
#      homebrew_cask: name={{ item }} state=present
#      with_items:
#        - yubikey-neo-manager
#        - yubikey-personalization-gui
#        - yubikey-piv-manager
#        - dropbox
#        - flash
#        - github
#        - google-chrome
#        - google-drive
#        - java
#        - vmware-fusion
#        - launchrocket
#        - gpgtools
#        - macpass
#        - microsoft-lync
#        - microsoft-office

    - name: brew linkapps
      command: brew linkapps
      tags:
          - skip_ansible_lint

    - name: install keybase-installer
      npm: 
        name: "{{ item }}"
        global: yes
        state: present
      with_items:
        - jslint
        - jsonlint
        - keybase-installer
        - vimlint

    - name: install keybase
      command: keybase-installer
      tags:
          - skip_ansible_lint

    - name: install pip
      easy_install:
          name: pip
          state: present
      become: yes

    - name: pip installs required python libraries
      pip:
          name: "{{ item }}"
          state: present
      with_items:
      - virtualenv
      - setuptools
      - requests[security]
      become: yes

    - name: create local run directory in case lldpd is installed
      file:
        path: /usr/local/var/run
        state: directory

    - name: link utilities to local
      file:
        dest: "/usr/local/bin/{{ item.name }}"
        src: "{{ item.src }}/{{ item.name }}"
        state: link
        force: yes
      with_items:
        - { src: '/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources', name: 'airport' }
        - { src: '/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support', name: 'lsregister' }

    - name: link utilities to local
      file:
        name: "/Applications/{{ item.name }}"
        src: "{{ item.src }}/{{ item.name }}"
        state: link
        force: yes
      with_items:
        - { src: '/Applications/Xcode.app/Contents/Developer/Applications', name: 'iOS Simulator.app' }
      become: yes
