---
- name: Common Play
  hosts: localhost
  connection: local

  tasks:
    - name: install osx build software
      homebrew: name={{ item }} state=present
      with_items:
        - Caskroom/cask/gpgtools
        - Caskroom/cask/macpass
        - autoconf
        - autoconf-archive
        - automake
        - boost
        - byobu
        - diffuse
        - gettext
        - gpg-agent
        - hub 
        - intltool
        - libevent
        - libmemcached
        - libtool
        - mysql
        - npm
        - pcre
        - protobuf
        - pwgen
        - qemu
        - splint
        - ssh-copy-id
        - swig
        - libyaml
        - yubico-piv-tool

# This is because not everything will install
    - name: install bison for OSX
      ignore_errors: yes
      homebrew: name={{ item }}
                state=present
      with_items:
        - bison
        - flex
        - gperf

    - name: install keybase-installer
      command: npm install -g keybase-installer
    - name: install keybase
      command: keybase-installer
    - name: disable hidden files on network filesystems
      command: defaults write com.apple.desktopservices DSDontWriteNetworkStores true

