#!/usr/bin/env ANSIBLE_HOSTS="localhost," ANSIBLE_CONNECTION=local ansible-playbook
#vim: set filetype=ansible.yaml softtabstop=2 shiftwidth=2 tselect=2 expandtab :
---
- name: Install Solarized
  hosts: localhost

  tasks:
    - name: Git solar
      git: 
        repo: https://github.com/tomislav/osx-terminal.app-colors-solarized.git
        dest: osx-terminal.app-colors-solarized

    - name: install
      raw: open  "osx-terminal.app-colors-solarized/Solarized Dark.terminal"
