---
- name: update brew
  homebrew:
      update_homebrew: yes
      upgrade_all: yes

- name: install osx build software
  homebrew: 
      name: "{{ item }}"
      state: present
  with_items: common_build

- name: Install from dupes
  homebrew_tap: name={{ item }}
                state=present
  with_items:
    - homebrew/dupes
    - caskroom/cask

- name: install brew cask
  command: brew install brew-cask
