#!/usr/bin/env ANSIBLE_HOSTS="localhost," ANSIBLE_CONNECTION=local ansible-playbook
# vim:ft=yaml
---
- name: install homebrew basics
  hosts: localhost

  roles:
    - homebrew
    - homebrew-common
