#!/usr/bin/env ANSIBLE_HOSTS="localhost," ANSIBLE_CONNECTION=local ansible-playbook
# vim:ft=yaml
---
- name: install homebrew basics
  hosts: localhost

  roles:
    - homebrew

  tasks:
    - name: update brew
      homebrew: update_homebrew=yes upgrade_all=yes

    - name: install osx build software
      package: name={{ item }} state=present
      with_items:
        - autoconf
        - autoconf-archive
        - automake
        - byobu
        - diffuse
        - gettext
        - intltool
        - libevent
        - libtool
        - libyaml
        - pcre
        - protobuf
        - pwgen
        - shellcheck
        - splint
        - ssh-copy-id
        - swig


    - name: Install additional taps
      homebrew_tap: name={{ item }}
                    state=present
      with_items:
        - homebrew/dupes

# This is because not everything will install
    - name: install bison and friends for OSX
      ignore_errors: yes
      homebrew: name={{ item }}
                state=present
      with_items:
        - bison
        - flex
        - gperf
        - engine_pkcs11

    - name: brew linkapps
      command: brew linkapps
